accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    AccountCreateView,
    AccountListView,
    ExpenseCategoryCreateView,
    ReceiptCreateView,
    ReceiptListView,
    ExpenseCategoryListView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path("accounts/", AccountListView.as_view(), name="accounts"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return f"{self.category} at {self.vendor} "

accounts/forms.py
from socket import fromshare
from django import forms

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import Account, Receipt, ExpenseCategory


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/expense_list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/account_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/expense_create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/account_create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("accounts")

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Home</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'create_receipt' %}">Create a Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'list_categories' %}">Categories</a>
                    </li>
                    <li>
                        <a href="{% url 'create_category' %}">Create a Category</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts' %}">Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create an Account</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% endif %}
                    {% if user.is_anonymous %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            {% block content %}
            <!---->
            {%  endblock content %}
        </main>
    </body>
</html>







{% comment %} {% if user.is_authenicated %}
                    <li>
                        <a href="{% url "logout" %}">Logout</a>
                    </li>
                    {% endif %}
                    <!---->
                    {% if user.is_anonymous %}
                    <li>
                        <a href="{% url "signup" %}">Sign Up</a>
                    </li>
                    <li>
                        <a href="{% url "login" %}">Login</a>
                    </li>
                    {% endif %} {% endcomment %}

receipts/templates/receipts/account_create.html
{% extends 'base.html' %}
<!---->
{% block content %}
<div>
  <h1>Create Account</h1>
  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button>Create</button>
  </form>
</div>
{% endblock content %}

receipts/templates/receipts/account_list.html
{% extends 'base.html' %}
<!---->
{% block content %}
<h1>Accounts</h1>
<p>
  <a href="{% url 'create_account' %}">Create Account</a>
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Number of Receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for item in account_list.all %}
    <tr>
      <td>{{ item.name }}</td>
      <td>{{ item.number }}</td>
      <td>{{ item.items.all }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}
<!---->
{% block content %}
<div>
  <h1>Create Receipt</h1>
  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button>Create</button>
  </form>
</div>
{% endblock content %}

receipts/templates/receipts/expense_create.html
{% extends 'base.html' %}
<!---->
{% block content %}
<div>
  <h1>Create Category</h1>
  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button>Create</button>
  </form>
</div>
{% endblock content %}

receipts/templates/receipts/expense_list.html
{% extends 'base.html' %}
<!---->
{% block content %}
<h1>Expense Categories</h1>
<p>
  <a href="{% url 'create_category' %}">Create</a>
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for category in expensecategory_list.all %}
    <tr>
      <td>{{ category.name }}</td>
      <td>{{ category.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
<!---->
{% block content %}
<h1>My Receipts</h1>
<table>
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Total</th>
      <th>Tax</th>
      <th>Date</th>
      <th>Category</th>
      <th>Account</th>
    </tr>
  </thead>
  <tbody>
    {% for item in receipt_list.all %}
    <tr>
      <td>{{ item.vendor }}</td>
      <td>{{ item.total }}</td>
      <td>{{ item.tax }}</td>
      <td>{{ item.date|date:"m-d-Y"}}</td>
      <td>{{ item.category }}</td>
      <td>{{ item.account }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}